services:
  app:
    container_name: app
    build:
      context: .
      target: app
      dockerfile: Dockerfile
    command: "npx nest start"
    networks:
      - helizium-network
    ports:
      - "${APP_PORT:-3500}:${APP_PORT:-3500}"
    environment:
      - PORT=${APP_PORT:-3500}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=ci
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--loglevel", "warning"]
    networks:
      - helizium-network

  db:
    container_name: db
    image: postgres:latest
    attach: false
    networks:
      - helizium-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /var/lib/postgresql/data

networks:
  helizium-network:
    external: ${NETWORK_EXTERNAL:-false}
