services:
  auth-service:
    container_name: auth-service
    build:
      context: .
      target: app
      dockerfile: Dockerfile
    command: "npm run migration:run && npm run start"
    networks:
      - helizium-network
    ports:
      - "${APP_PORT:-3500}:${APP_PORT:-3500}"
    env_file:
      - path: .env
        required: false
    environment:
      - PORT=${APP_PORT:-3500}
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=ci
    depends_on:
      - redis
      - db

  redis:
    container_name: redis
    image: redis:latest
    command: ["redis-server", "--loglevel", "warning"]
    networks:
      - helizium-network
    volumes:
      - redis-data:/data

  db:
    container_name: db
    image: postgres:latest
    attach: false
    networks:
      - helizium-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql

networks:
  helizium-network:
    external: ${NETWORK_EXTERNAL:-false}

volumes:
  postgres-data:
  redis-data:
