apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    {{- include "ecommerce-app.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.config.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.config.user | quote }}
