apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "3500"
  NODE_ENV: ci
  REDIS_URL: redis://redis:6379
  GRPC_SERVER_URL: 0.0.0.0:50051
  API_GATEWAY_TOKEN_REVOKE_URL: http://localhost:9000/add
  OTLP_COLLECTOR_URL: http://localhost:4317
  EMAIL_HOST: smtp.gmail.com
  EMAIL_PORT: "587"
  EMAIL_FROM: account@gmail.com
  EMAIL_USER: account@gmail.com
  CONFIRM_EMAIL_FRONTEND_URL: https://helizium.com/email/confirm/:userId/:otp
  RESET_PASSWORD_FRONTEND_URL: https://example.com/reset-password/:userId/:token
  BCRYPT_SALT_ROUNDS: "10"
  TOTP_SECRET_SIZE: "20"
  API_TOKENS_LIMIT_PER_USER: "5"
  JWT_ACCESS_TTL: "900"
  JWT_REFRESH_TTL: "604800"
  TOTP_INIT_TTL: "900"
  EMAIL_CONFIRMATION_CODE_TTL: "43200"
  EMAIL_MFA_CODE_TTL: "1800"
  EMAIL_RESET_PASSWORD_LINK_TTL: "21600"
  EMAIL_TIME_TO_VERIFY_COOKIE: "300"
  API_TOKENS_JTI_CACHE_TTL: "3600"
